<?php return array (
  'is_live' => '0',
  'close_msg' => 'Down for maintenance',
  'site_url' => 'http://localhost/AlumNation/public',
  'site_name' => 'Alum Nation',
  'site_logo' => '/assets/images/logo/1689668015_64b649af77ffb_logo-icon.png',
  'app_name' => 'AlumNationCode',
  'favicon_icon' => '/assets/images/logo/1689667124_64b64634a7230_logo-icon.png',
  'favicon_icon_apple' => '/assets/images/logo/1689666983_64b645a76448f_logo-icon.png',
  'newsletter_subscribe' => '0',
  'notify_email_address' => 'weruz@mailinator.com',
  'notify_messages_status' => '0',
  'notify_comments_status' => '0',
  'MAIL_MAILER' => 'smtp',
  'MAIL_HOST' => 'sandbox.smtp.mailtrap.io',
  'MAIL_PORT' => '2525',
  'MAIL_USERNAME' => 'ca6e7d4b7e540c',
  'MAIL_PASSWORD' => 'c729650da89390',
  'MAIL_ENCRYPTION' => 'tls',
  'MAIL_FROM_ADDRESS' => 'support@qproduct.net',
  'MAIL_FROM_NAME' => 'APP_NAME',
  'facebook_link' => 'https://www.bycokepuxex.me.uk',
  'twitter_link' => 'https://www.fulureqobaky.me.uk',
  'instagram_link' => 'https://www.tomiqawynewibyb.org.uk',
  'youtube_link' => 'https://www.qafuq.us',
  'linkedin_link' => 'https://www.lebymuby.com',
  'pinterest_link' => 'https://www.diduxavazipuqol.net',
  'whatsapp_link' => 'https://www.jivimimuwo.me.uk',
  'snapchat_link' => 'https://www.mav.cm',
  'tumblr_link' => 'https://www.zadino.net',
  'meta_keywords' => 'Meta Key, AlumNation, website',
  'meta_description' => 'AlumNation meta description',
  'meta_title' => 'AlumNation meta title',
  'meta_image' => 'assets/uploads/seo/2023/03/28/202303288343.png',
  'PAYPAL_ACTIVE' => false,
  'PAYPAL_CLIENT_ID' => 'AYYaAaNKLpw1_KI8bsPWMzHky2qwTo3qOv4yM4LfjMitAUuU22mbVIrgrgqvNqS_9OMMsMRo4gatQNN1',
  'PAYPAL_APP_SECRET' => 'AYYaAaNKLpw1_KI8bsPWMzHky2qwTo3qOv4yM4LfjMitAUuU22mbVIrgrgqvNqS_9OMMsMRo4gatQNN1',
  'BANK_STATUS' => true,
  'ABOUT_BANK' => 'Write some message',
  'BANK_NAME' => 'City Bank',
  'ACCOUNT_NUMBER' => '12344355434',
  'ACCOUNT_NAME' => 'Business account',
  'SWIFT_CODE' => 'City Bank',
  'ROUTING_NUMBER' => '223123',
  'STRIPE_ACTIVE' => true,
  'STRIPE_KEY' => 'pk_test_jdAIT8RDQfnjcMBLiLF6MvpD',
  'STRIPE_SECRET' => 'sk_test_wpBQp1dlHFljKeyrhqLSXBlK',
  'RAZORPAY_ACTIVE' => true,
  'RAZORPAY_KEY' => 'rzp_test_qs2qz7KKUQbpgo',
  'RAZORPAY_SECRET' => 'PpcKi4Tlfx86Dtz2u9kDPxm1',
  'AAMARPAY_ACTIVE' => true,
  'AAMARPAY_STORE' => 'test',
  'AAMARPAY_KEY' => 'test',
  'MOLLIE_ACTIVE' => true,
  'MOLLIE_KEY' => 'test_7WRmUeVGdRTG5G4Kk34rcaDgjxuUHj',
  'MOLLIE_Partner_ID' => '16905249',
  'MOLLIE_Profile_ID' => 'pfl_n3GFjcQ4EN',
  'tawk_to' => true,
  'tawk_direct_link' => NULL,
  'tawk_script' => NULL,
  'pwa_active' => true,
  'open_ai_model' => 'text-davinci-003',
  'heading_title' => 'Write your Business Idea with',
  'contact_address' => 'Ut modi ex corrupti',
  'contact_phone' => '+1 (151) 373-7979',
  'contact_fax' => '+1 (101) 738-7754',
  'contact_mobile' => '+1 (144) 937-1774',
  'contact_email' => 'veru@mailinator.com',
  'working_hour' => 'Tempora exercitation',
  'custom_css' => '.test{
color: white
}
.test-too{
background-color: dark
}',
);